// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $img_world_svg from "./routes/img/world.svg.ts";
import * as $index from "./routes/index.tsx";
import * as $legal from "./routes/legal.tsx";
import * as $notes_slug_ from "./routes/notes/[slug].tsx";
import * as $photos_china from "./routes/photos/china.tsx";
import * as $photos_germany from "./routes/photos/germany.tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $Gallery from "./islands/Gallery.tsx";
import * as $ImageCollection from "./islands/ImageCollection.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/img/world.svg.ts": $img_world_svg,
		"./routes/index.tsx": $index,
		"./routes/legal.tsx": $legal,
		"./routes/notes/[slug].tsx": $notes_slug_,
		"./routes/photos/china.tsx": $photos_china,
		"./routes/photos/germany.tsx": $photos_germany,
		"./routes/projects/index.tsx": $projects_index,
	},
	islands: {
		"./islands/Gallery.tsx": $Gallery,
		"./islands/ImageCollection.tsx": $ImageCollection,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
